language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
allow_failures:
  - rvm: ruby-head
branches:
  only:
    - master
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
script:
  - "bundle exec rake"
